#test
name: Trigger Central Code Scan

on:
  push:
    branches:
      - main

jobs:

  trigger-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Central Code Scan
      env:
        CENTRAL_REPO_URL: https://api.github.com/repos/amalynnpham/ASHDemo/dispatches
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             $CENTRAL_REPO_URL \
             -d '{"event_type":"external-repo-push","client_payload":{"repo":"https://github.com/amalynnpham/testHooksRepo"}}'
